### ISSUE TITLE
Custom shared EFS across nodes

### ISSUE THREAD

**Issue by jwillis0720** [aws-samples/aws-plugin-for-slurm#1]
If I understand correctly, the head node is runnings as an NFS server and sharing `/nfs` across nodes. Is it possible to mount my EFS instead? First things first, how can I turn the head_node.yml to use a custom VPC rather than create its own. Is that recommended?

**Comment by amrragab8080** [comment]
Sure consider that the `/nfs` created by the automation is not mutually exclusive to other managed mounts. However I would recommend keeping the `/nfs` since its relatively light traffic ensuring the slurm configuration is available across the growing compute nodes. And you can mount your workload specific data onto other paths.

And yes you can use an existing VPC as this is just a POC to lay down an example landing zone. Fork this repo and create a parameter in the CF which accepts a VPC ID and pass that ID into the CF Resources that reference the VpcID. You will not need this in the CF:
```
VPC:
   Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      Tags:
      - Key: Name
        Value: HPC VPC
```
